Handle empty root site collection in a web application.
googlegsa/sharepoint pull request #14
Opened 2017-05-23 19:33 UTC by lavanyachandramouli

Fix for b/33263458.

2017-05-23 23:41 UTC, wiarlawd requested changes

2017-05-23 23:41 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        log.log(Level.WARNING, "Ensure web application has root site created."
There are missing spaces in the message at the line breaks, and no placeholder for the getVirtualServerUrl() argument, but I don't think the extra text here is useful, and so this is a log-and-throw anti-pattern. I would just include the URL in the exception text and drop the logging statement.

2017-05-23 23:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +    MockSoapFactory rootMissingSoapFactory = MockSoapFactory.blank().endpoint(VS_ENDPOINT,
80 cols in a few places here.

2017-05-23 23:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +        .register(VS_CONTENT_EXCHANGE).register(CD_CONTENT_EXCHANGE)
Split these onto 3 lines consistently here and below.

2017-05-23 23:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +            .register(ROOT_SITE_SAW_EXCHANGE)
Why is the order changing from place to place?

2017-05-24 17:58 UTC, lavanyachandramouli commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        log.log(Level.WARNING, "Ensure web application has root site created."
Done.

2017-05-24 17:58 UTC, lavanyachandramouli commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +    MockSoapFactory rootMissingSoapFactory = MockSoapFactory.blank().endpoint(VS_ENDPOINT,
Done. Thank you.

2017-05-24 17:58 UTC, lavanyachandramouli commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +        .register(VS_CONTENT_EXCHANGE).register(CD_CONTENT_EXCHANGE)
Done.

2017-05-24 17:59 UTC, lavanyachandramouli commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +            .register(ROOT_SITE_SAW_EXCHANGE)
Done.

2017-05-24 21:38 UTC, wiarlawd approved these changes

2017-05-24 22:16 UTC, merged