Handle discussion reply:
googlegsa/sharepoint pull request #17
Opened 2017-08-02 21:04 UTC by lavanyachandramouli

1. Update Title value with parent discussion title
2. Add source url parameter in display url. On click of Ok, SP navigates
back to parent discussion thread instead of list.

2017-08-04 01:10 UTC, wiarlawd requested changes

2017-08-04 01:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +          String sourceURL = row.getAttribute("ows_FileDirRef").split(";#")[1];
s/sourceURL/sourceUrl/. Use OWS_FILEDIRREF_ATTRIBUTE. Add 2 as second argument to split (mainly for consistency).

2017-08-04 01:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        if ("Message".equals(contentType)) {
This should go before the check of canRespondWithNoContent just above this.

2017-08-04 01:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        // There is no title field for content type: Message.
I think briefer is OK here, just a one line comment:

// There is no title field for discussion replies, use DiscussionTitle.

2017-08-04 01:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +  private static final String OWS_CONTENTTYPE_ATTRIBUTE = "ows_ContentType";
Add javadoc.

2017-08-04 01:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +      String contentType = row.getAttribute(OWS_CONTENTTYPE_ATTRIBUTE);
Move this to just before the if, at least, maybe inline it.

2017-08-04 01:10 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +        + "<td>sites/SiteCollection/Lists/Custom List/Test Folder</td></tr>"
Indent like the other second columns?

2017-08-04 22:45 UTC, lavanyachandramouli commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +  private static final String OWS_CONTENTTYPE_ATTRIBUTE = "ows_ContentType";
Done

2017-08-04 22:45 UTC, lavanyachandramouli commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +      String contentType = row.getAttribute(OWS_CONTENTTYPE_ATTRIBUTE);
Done

2017-08-04 22:46 UTC, lavanyachandramouli commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        if ("Message".equals(contentType)) {
Acknowledge

2017-08-04 22:46 UTC, lavanyachandramouli commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        // There is no title field for content type: Message.
Done

2017-08-04 22:46 UTC, lavanyachandramouli commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +          String sourceURL = row.getAttribute("ows_FileDirRef").split(";#")[1];
Done

2017-08-04 22:46 UTC, lavanyachandramouli commented on test/com/google/enterprise/adaptor/sharepoint/SharePointAdaptorTest.java
> +        + "<td>sites/SiteCollection/Lists/Custom List/Test Folder</td></tr>"
Done

2017-08-09 00:00 UTC, wiarlawd approved these changes
LGTM++ with a nit.

2017-08-09 00:00 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointAdaptor.java
> +        // discussion replies will be of content type "Message".
Comment wasn't changed. Replace with a one-liner and indent two spaces:

// There is no title field for discussion replies, use DiscussionTitle.

2017-08-09 00:01 UTC, wiarlawd commented
Oh, and update the commit message a bit. The colon is jarring, because the first line is used stand-alone. See if there's a longer title that is more clear (up to 58 characters), or just change colon to period.

2017-08-09 19:29 UTC, merged