print username used by SP connector for NTLM
googlegsa/sharepoint pull request #4
Opened 2017-03-09 22:24 UTC by sergres

print process owner username in case of fallback to NTLM authentication (windows integrated
authentication).
Here is test table:
https://docs.google.com/a/google.com/spreadsheets/d/1BcAewlv3bEuP4t-o9E3-4cPLf30ax1xF5fBS2BwA6WY/edit?usp=sharing

2017-03-10 23:11 UTC, lavanyachandramouli approved these changes
LGTM.

2017-03-11 00:06 UTC, wiarlawd requested changes
Formatting nits. Please amend the commit (git commit --amend) and force push (git push -f).

John L

2017-03-11 00:06 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointFormsAuthenticationHandler.java
> +import com.google.enterprise.adaptor.sharepoint.SharePointAdaptor;
This goes first, not last. Also, a static import is probably better, and those go first in a separate block before the other imports.

2017-03-11 00:06 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointFormsAuthenticationHandler.java
> +          SharePointAdaptor.getAdaptorUser("")});
Either with spaces inside braces or without is fine, but not a mix. Once getAdaptorUser is statically imported and the whole array fits on one line, break before new Object[] for a higher-level line break.

2017-03-15 19:42 UTC, wiarlawd requested changes
One more nit. It's user-visible or I might have let it go.

John L

2017-03-15 19:42 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/sharepoint/SharePointFormsAuthenticationHandler.java
> +          + "Adaptor will fallback to use windows integrated authentication."
Change the final . to space, as you did above.

2017-03-15 20:46 UTC, wiarlawd approved these changes

2017-03-15 20:47 UTC, merged