Fixing the library title for Sharepoint User Profiles (b/21765085)
googlegsa/sharepoint pull request #5
Opened 2017-03-17 13:57 UTC by mpaggi

Implementation title for Google Adaptor Sharepoint User Profiles
is the same as for the SharePoint Google Adaptor for SharePoint
Fixing it by setting up two different variables in the build file.

2017-03-17 22:01 UTC, wiarlawd requested changes
A nit and a suggestion.

John L

2017-03-17 22:01 UTC, wiarlawd commented on build.xml
> +            value="${adaptor.title}"/>
It looks like all three of these edited & added attribute elements will now fit on one line.

2017-03-17 22:01 UTC, wiarlawd commented on build.xml
> +    value="Google Adaptor for SharePoint"/>
While you're doing this, you could also update these titles to be correct:

Google Search Appliance Connector for SharePoint
Google Search Appliance Connector for SharePoint User Profiles

2017-03-20 09:47 UTC, mpaggi commented
Thanks, done.

2017-03-20 20:11 UTC, wiarlawd approved these changes

2017-03-20 20:12 UTC, merged